### ISSUE TITLE
"The invoked member is not supported in a dynamic assembly" when creating SvgImage from XAML?

### ISSUE THREAD

**Issue by DaveInCaz** [ElinamLLC/SharpVectors#124]
My WPF project uses `SvgImage `but I am getting an exception when the XAML form tries to load.

The project builds the XAML form into an assembly which is loaded by an unmanaged EXE at runtime through COM interop.

`SvgImage `is used as follows:

```
<Fluent:SplitButton
 ...
   l:RibbonImages.Source="{svgc:SvgImage Source=path/to/Images/filename.svg}">
```

What happens here is that `l:RibbonImages` is a `DependencyObject `that binds its source to some properties of the object its attached to. It does nothing directly to the SVG object itself; it just passes it through, essentially.

The immediate exception thrown is on that line of XAML code:
`'System.Windows.Markup.XamlParseException' in PresentationFramework.dll` but I think this is rather generic; the inner exception is more interesting, and is as follows:

```
Message	"Could not load file or assembly 'SharpVectors.Converters.Wpf, PublicKeyToken=b532964b8548be77' or one of its dependencies. The system cannot find the file specified."	string

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveAssembly(BamlAssembly bamlAssembly)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlTypeToType(BamlType bamlType)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)
   at System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   at System.Windows.Baml2006.Baml2006Reader.Read()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   
```

So basically it claims to fail to load the assembly at runtime - even though it builds fine & the DLL is copied to the output directory.

However at runtime in fact the DLL is not shown as loaded  in the Visual Studio debugger Modules window.

------

Now an interesting variation in this inner exception will occur if I add a dummy line of code to a plain CS file in the project:

`public static SharpVectors.Converters.SvgControl dummy = new SharpVectors.Converters.SvgControl();`

The point of this line was just to see if it would throw _there_ instead of in XAML. But in fact this line executes fine; since its `static` it goes early and a breakpoint confirms it runs OK.

Later when it tries to load the XAML I get an exception on the same line as above, but the inner details are different:

```
InnerException	{"The invoked member is not supported in a dynamic assembly."}	System.Exception {System.NotSupportedException}

   at System.Reflection.Emit.InternalAssemblyBuilder.get_CodeBase()
   at SharpVectors.Converters.SvgImageBase.<>c.<GetEntryAssembly>b__24_4(Assembly assembly) in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\SvgImageBase.cs:line 410
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at SharpVectors.Converters.SvgImageBase.GetEntryAssembly() in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\SvgImageBase.cs:line 408
   at SharpVectors.Converters.SvgImageBase.GetAppName() in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\SvgImageBase.cs:line 356
   at SharpVectors.Converters.SvgImageExtension..ctor() in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\SvgImageExtension.cs:line 51

```  

AFAIK there is no dynamic assembly creation going on, so I have no idea what this means. But in this scenario I can see that the DLL is loaded in the debugger.

My hunch is that both of these failure variants have the same root cause and just manifests itself differently depending on what code runs first.

Basically I'm at a loss how to debug this any further. But I hoped the latter information about how the CodeBase property fails might be a useful clue.

Thanks

**Comment by paulushub** [comment]
@DaveInCaz Thanks for the information. Please give me information on the `Fluent:SplitButton` button.

**Comment by DaveInCaz** [comment]
@paulushub Fluent:SplitButton comes from https://github.com/fluentribbon/Fluent.Ribbon.

I discovered that I can get the same error by doing either this:

```
                    <Fluent:SplitButton
                        LargeIcon="{svgc:SvgImage Source=..../file.svg}"
                        >
```

(ie without my custom attached property in use)

or this:

` <Image Source="{svgc:SvgImage Source=..../file.svg}"/>`

So I don't think the 'destinaton' of the SVG image is related to the problem.

---

One note - previously I've used SharpVectors within a simpler EXE project. But now I'm using it within a sub-assembly that is loaded separately. Since this is an assembly load error I wonder if that is relevant somehow?

**Comment by DaveInCaz** [comment]
@paulushub  as I've done more investigation  I tried out several configurations and I think it is some specific details of how my app works that seem to be relevant. Specifically, my assembly which uses SV is itself called through interop from an unmanaged program.

I also posted a related question here: https://stackoverflow.com/questions/60118880/wpf-assembly-called-through-com-interop-produces-system-windows-markup-xamlpars

**Comment by DaveInCaz** [comment]
In fact, I can reproduce this now with controls from other libraries. So this doesn't seem likely to be a problem specific to SharpVectors.

**Comment by paulushub** [comment]
@DaveInCaz Thanks for the updates. Please look into the following and see if they are related?

[Loading plug-in DLL files...](https://stackoverflow.com/questions/10091221/loading-plug-in-dll-files-the-invoked-member-is-not-supported-in-a-dynamic-ass)
[NotSupportedException: The invoked member is not supported in a dynamic module in C# Unity 5](https://stackoverflow.com/questions/44446720/notsupportedexception-the-invoked-member-is-not-supported-in-a-dynamic-module-i)

Also, have you registered the .NET Assemblies? 
[Regasm.exe (Assembly Registration Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/regasm-exe-assembly-registration-tool)

**Comment by DaveInCaz** [comment]
@paulushub, thanks for those links. The one about loading dynamic modules is interesting.

I have an AssemblyResolve event handler, to try & manually load the SV assembly. When I do that and return the assembly correctly, I get a second exception (below).

This exception originates in `SvgImageBase.GetEntryAssembly()` on the line that tries to get the `CodeBase`.

So it seems like in my case this assembly is trying to be loaded in some kind of dynamic fashion, and so this constructor fails. This is similar to the linked article.

(Note that CodeBase is read also in the catch block - I'm not sure if that is the main problem but it seems a little risky to call have a function that can potentially throw in a catch block.)

Reading the code this seems related to the use of `_appname` ... which seems optional. Can I avoid this somehow?


```
   at System.Reflection.Emit.InternalAssemblyBuilder.get_CodeBase()
   at SharpVectors.Converters.SvgImageBase.<>c.<GetEntryAssembly>b__24_4(Assembly assembly) in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\SvgImageBase.cs:line 410
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at SharpVectors.Converters.SvgImageBase.GetEntryAssembly() in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\SvgImageBase.cs:line 408
   at SharpVectors.Converters.SvgImageBase.GetAppName() in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\SvgImageBase.cs:line 356
   at SharpVectors.Converters.SvgImageExtension..ctor() in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\SvgImageExtension.cs:line 51

```

**Comment by DaveInCaz** [comment]
I tried to set AppName manually but since GetAppName() is called within the SvgImageBase constructor, it doesn't help.

**Comment by DaveInCaz** [comment]
Okay, I think I found the definitive reason for this...

Source: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getentryassembly?view=netframework-4.8

> **Remarks**
> The GetEntryAssembly method can return null when a managed assembly has been loaded from an unmanaged application. For example, if an unmanaged application creates an instance of a COM component written in C#, a call to the GetEntryAssembly method from the C# component returns null, because the entry point for the process was unmanaged code rather than a managed assembly.

This is exactly what I'm doing. My EXE is unmanaged, and eventually down the call chain it uses SharpVectors.

It looks like SV is using this code to try to detect if it is running in the Visual Studio designer? Maybe there is some other way to detect that?

**Comment by DaveInCaz** [comment]
(clicked CLOSE by mistake)

**Comment by paulushub** [comment]
@DaveInCaz Looking into the issue to see how to resolve it, sorry for any inconvenience.

**Comment by DaveInCaz** [comment]
@paulushub  thanks! That's ok, and I realize that this issue became sort of just a log of my debugging activities.

I've opened one other issue with what I think is a specific related problem: https://github.com/ElinamLLC/SharpVectors/issues/125

I have to go through some other notes and see if there's anything else to this present issue or if I can just close it now. 

BTW I've been really happy to use this library all throughout, this is the first time I've run into any significant issue at all; thanks for the work of the project contributors :)

**Comment by paulushub** [comment]
The multi-targets release 1.6 is now active.
