### ISSUE TITLE
Handling of invalid svg files

### ISSUE THREAD

**Issue by mcdikki** [ElinamLLC/SharpVectors#146]
If you pass invalid svg data to the SvgViewBoxs StreamSource or SvgSource property via binding in WPF, it throws an exception which crashes the whole app.  
Since this happens in the UI thread and in the WPF code base, it's not (to my knowledge) possible to catch those exceptions and handle them appropriate.  
As a workaround, I catch all unhandled exceptions and ignore them silently which is not the optimal solution. 

Is there any chance we can make the WPF controls more robust against invalid data?  

I'm not in control of the SVG data in my current use case and can't sanitize it in advance.

This is the relevant part of the exceptions stack trace:
```
Ausnahme ausgelöst: "System.Xml.XmlException" in System.Private.Xml.dll
Ausnahme ausgelöst: "System.Xml.XmlException" in SharpVectors.Converters.Wpf.dll
Ausnahme ausgelöst: "System.Reflection.TargetInvocationException" in System.Private.CoreLib.dll
System.Windows.Data Error: 8 : Cannot save value from target back to source. BindingExpression:Path=DataContext.Service.Schnittplan; DataItem='DataGrid' (Name=''); target element is 'DataGrid' (Name=''); target property is 'SelectedItem' (type 'Object') XmlException:'System.Xml.XmlException: 'y' is an unexpected token. Expecting whitespace. Line 1, position 5701.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at SharpVectors.Dom.Css.CssXmlDocument.Load(XmlReader reader) in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorCss\Css\CssXmlDocument.cs:line 209
   at SharpVectors.Dom.Svg.SvgDocument.Load(TextReader txtReader) in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorModel\DocumentStructure\SvgDocument.cs:line 465
   at SharpVectors.Renderers.Utils.WpfSvgWindow.LoadDocument(TextReader textReader, WpfDrawingSettings drawingSettings) in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorRenderingWpf\Utils\WpfSvgWindow.cs:line 156
   at SharpVectors.Converters.FileSvgReader.LoadFile(TextReader textReader) in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\FileSvgReader.cs:line 653
   at SharpVectors.Converters.FileSvgReader.Read(TextReader svgTextReader) in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\FileSvgReader.cs:line 354
   at SharpVectors.Converters.SvgViewbox.CreateDrawing(String svgSource, WpfDrawingSettings settings) in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\SvgViewbox.cs:line 1458
   at SharpVectors.Converters.SvgViewbox.CreateDrawing() in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\SvgViewbox.cs:line 1240
   at SharpVectors.Converters.SvgViewbox.OnSettingsChanged() in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\SvgViewbox.cs:line 1168
   at SharpVectors.Converters.SvgViewbox.OnSvgSourceChanged(DependencyObject obj, DependencyPropertyChangedEventArgs args) in D:\Visual Studio\Workspaces\SharpVectors\Source\SharpVectorConvertersWpf\SvgViewbox.cs:line 1646
```

To be clear, the svg data is broken in this case and the exception makes total sense. There is a whitespace missing in the xml of the svg. 
But I would like to just ignore errors and handle it like a null value instead.
Maybe it would make sense to add an optional DP to the WPF control to delegate errors to an handler or such.
Something like:
```
<svgc: SvgViewBox SvgSource="{Binding SvgData}" OnError="OnSvgError" />
```

```
public void OnSvgError(object sender, Exception exception) {
    // Handle the error here
}
```

Thanks.

**Comment by paulushub** [comment]
Yes, it is planned. It will be part of the next release and was discussed in the issue #141.
Some still prefer the exception, which is not thrown in design mode. 
The plan is to add it similar to the one currently added to the `GdiSvgControl`, if not handled it will be thrown.

**Comment by paulushub** [comment]
@mcdikki The current commit adds the support for the events, please give it a try.
