### ISSUE TITLE
FormatException with some SVG files

### ISSUE THREAD

**Issue by Odirb** [ElinamLLC/SharpVectors#149]
Hello,
Convertion from SVG to Xaml fail with the attached file, with this exception :

```
Converting: C:\Data\Downloads\label.svg
Error: Exception (System.FormatException)
Input string was not in a correct format.
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at SharpVectors.Dom.Svg.SvgNumber.ScientificToDec(String sc)
   at SharpVectors.Dom.Svg.SvgLength.GetCssXmlValue()
   at SharpVectors.Dom.Svg.SvgLinearGradientElement.get_X1()
   at SharpVectors.Renderers.Wpf.WpfGradientFill.GetLinearGradientBrush(SvgLinearGradientElement res, Transform viewBoxTransform)
   at SharpVectors.Renderers.Wpf.WpfGradientFill.GetBrush(Rect elementBounds, WpfDrawingContext context, Transform viewTransform)
   at SharpVectors.Renderers.Wpf.WpfSvgPaint.GetBrush(Geometry geometry, String propPrefix, Boolean setOpacity)
   at SharpVectors.Renderers.Wpf.WpfPathRendering.RenderGroup(WpfDrawingRenderer renderer)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElement(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElementChildren(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElement(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElementChildren(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElement(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElementChildren(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElement(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElementChildren(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElement(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElementChildren(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElement(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElementChildren(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.RenderElement(ISvgElement svgElement)
   at SharpVectors.Renderers.Wpf.WpfRenderingHelper.Render(ISvgDocument docElement)
   at SharpVectors.Renderers.Wpf.WpfDrawingRenderer.Render(ISvgDocument node)
   at SharpVectors.Converters.FileSvgReader.LoadFile(String fileName)
   at SharpVectors.Converters.FileConverterOutput.OnWorkerDoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

```
[label.zip](https://github.com/ElinamLLC/SharpVectors/files/5169693/label.zip)

**Comment by paulushub** [comment]
@Odirb Thanks for reporting this issue. The updated regular expression for parsing numbers was not applied to the parsing in the `SharpVectors.Dom.Svg.SvgNumber.ScientificToDec` method.
This issue is now resolved, please verify.

**Comment by Odirb** [comment]
Hello @paulushub,
Thanks you for fixing this issue so quickly, it's perfectly fine now.
